version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/work:delegated
      - node_modules:/work/node_modules:delegated
    ports:
      - "5173:5173"
    command: npm run dev

volumes:
  node_modules:
